<a href="https://colab.research.google.com/github/anju4538/demo/blob/main/SampleDataTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
l = [1,2,3,4,5,6,7,1,2,3]
#convert list into series
s = pd.Series(l)
print(s) #convert the list in series
print(type(s)) #type of the s variable
print(s.dtype) # type of the every varible in the data

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    1
8    2
9    3
dtype: int64
<class 'pandas.core.series.Series'>
int64

In [7]:
# create a list with multi - datatype values and convert it into list and check data type of every element

l1 = [1,2,3,4,"CoDing SeeKho", 6.7,82.3,4,5]
obj = pd.Series(l1)
print(type(obj))
print(obj.dtype)

<class 'pandas.core.series.Series'>
object

**SERIES:**

1. single column
2. Order is maintained
3. 1 Dimensional
4. Tuple, list, set

In [8]:
# Convert the set in list

s = {1,2,2,3,4,3,5,6,7,8,8,9,10}
pd.Series(s)

TypeError: 'set' type is unordered

In [9]:
# Convert the set in list

s = {1,2,2,3,4,3,5,6,7,8,8,9,10}
try:
  pd.Series(s)
except TypeError:
  print("Set cannot be convert into series.")

Set cannot be convert into series.

In [11]:
# for that we have to convert the set in the list

s = {1,2,2,3,4,3,5,6,7,8,8,9,10}
s1 = list(s)
s1 = pd.Series(s1)
print(s1)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

**DataFrames**

2 - Dimensional
Rows and columns
Collection of series
Dictionary - key value pair

In [18]:
d = {
    "Name" : ["CoDing", "SeeKho", "Vikas Sir"],
    "Date" : ["10/02/2025", "08/03/2025", "23/01/2025"],
    "Temp" : [32, 35, 25]
}
d1 = pd.DataFrame(d)

In [19]:
# Convert data-type of data-frame and check data-type of every variable

print(type(d1))
print(d1.dtype)

<class 'pandas.core.frame.DataFrame'>

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [ ]:
# We canot find the dtype of the dictionary because it stores diffrent values so that's why it throws the Attribute Error.

# dictionary does not support in the find the evey variable data type.
#for that it uses indexing way to find the dtype in dataframe.

**DataSet:**

collection of dataframe is called dataset

In [21]:
rd = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(rd)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]

In [22]:
rd2 = pd.read_csv("/content/sample_data/mnist_test.csv")
rd2

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Attribiutes of dataframe**

1. shape
2. columns
3. index

In [23]:
rd.shape

(3000, 9)

In [24]:
rd.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [25]:
rd.index

RangeIndex(start=0, stop=3000, step=1)

In [26]:
#find the length of the dataframe

print(len(rd.index))

3000

**1. Read all the csv file that is given in the sample data**

**2. Download csv file**

**3. Practice all the operations that we have did today.**

In [30]:
# 1. read the california_housing_test.csv

rd1 = pd.read_csv("/content/sample_data/california_housing_test.csv")
rd1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [32]:
rd1.shape

(3000, 9)

In [34]:
rd1.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [35]:
rd1.index

RangeIndex(start=0, stop=3000, step=1)

In [37]:
print(type(rd1))

<class 'pandas.core.frame.DataFrame'>

In [38]:
rd2 = pd.read_csv("/content/sample_data/california_housing_train.csv")
rd2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [39]:
rd2.shape

(17000, 9)

In [40]:
rd2.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [41]:
rd2.index

RangeIndex(start=0, stop=17000, step=1)

In [42]:
print(type(rd2))

<class 'pandas.core.frame.DataFrame'>

In [43]:
rd3 = pd.read_csv("/content/sample_data/mnist_test.csv")
rd3

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
rd3.shape

(9999, 785)

In [45]:
rd3.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

In [46]:
rd3.index

RangeIndex(start=0, stop=9999, step=1)

In [47]:
print(type(rd3))

<class 'pandas.core.frame.DataFrame'>

In [49]:
rd4 = pd.read_csv("/content/sample_data/mnist_train_small.csv")
rd4

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
rd4.shape

(19999, 785)

In [51]:
rd4.columns

Index(['6', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.581', '0.582', '0.583', '0.584', '0.585', '0.586', '0.587', '0.588',
       '0.589', '0.590'],
      dtype='object', length=785)

In [52]:
rd4.index

RangeIndex(start=0, stop=19999, step=1)

In [53]:
print(type(rd4))

<class 'pandas.core.frame.DataFrame'>